In [1]:
import pandas as pd
import numpy as np
import os

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

In [2]:
train = pd.read_csv(r'C:\Users\dlwks\OneDrive\바탕 화면\VSCode\DACON_CODE_REVIEW\감귤 착과량\train.csv')
test = pd.read_csv(r'C:\Users\dlwks\OneDrive\바탕 화면\VSCode\DACON_CODE_REVIEW\감귤 착과량\test.csv')

In [3]:
train

,ID,착과량(int),수고(m),수관폭1(min),수관폭2(max),수관폭평균,2022-09-01 새순,2022-09-02 새순,2022-09-03 새순,2022-09-04 새순,...,2022-11-19 엽록소,2022-11-20 엽록소,2022-11-21 엽록소,2022-11-22 엽록소,2022-11-23 엽록소,2022-11-24 엽록소,2022-11-25 엽록소,2022-11-26 엽록소,2022-11-27 엽록소,2022-11-28 엽록소
0,TRAIN_0000,692,275.0,287.0,292.0,289.5,2.8,2.8,2.7,2.7,...,70.978249,70.876794,70.705253,70.559603,70.427356,70.340491,70.293830,70.262422,70.169841,70.043251
1,TRAIN_0001,534,293.0,284.0,336.0,310.0,3.3,3.3,3.3,3.2,...,71.535483,71.382303,71.253604,71.092665,70.955608,70.796630,70.597550,70.565088,70.560502,70.427600
2,TRAIN_0002,634,300.0,392.0,450.0,421.0,3.0,2.9,2.9,2.9,...,71.279804,71.199570,71.144020,71.026740,70.920038,70.876723,70.710129,70.595971,70.418203,70.399578
3,TRAIN_0003,639,289.0,368.0,379.0,373.5,3.1,3.0,3.0,3.0,...,69.934615,69.884124,69.845683,69.794682,69.779813,69.614644,69.455404,69.281590,69.238689,69.133970
4,TRAIN_0004,496,306.0,353.0,358.0,355.5,3.7,3.6,3.6,3.6,...,68.313016,68.285364,68.209860,68.209458,68.040083,67.859963,67.775556,67.701456,67.504244,67.410093
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2202,TRAIN_2202,119,230.0,353.0,367.0,360.0,4.7,4.6,4.5,4.5,...,66.347384,66.293609,66.193131,66.176590,66.109845,66.008775,65.889675,65.734066,65.586656,65.560547
2203,TRAIN_2203,611,266.0,337.0,400.0,368.5,3.1,3.0,3.0,3.0,...,73.438844,73.432194,73.355195,73.329491,73.271361,73.088750,73.071705,73.069036,72.952559,72.944396
2204,TRAIN_2204,650,237.0,353.0,362.0,357.5,3.0,3.0,2.9,2.9,...,67.576066,67.404347,67.394009,67.247428,67.117025,66.933771,66.734617,66.572095,66.506006,66.479459
2205,TRAIN_2205,363,281.0,337.0,403.0,370.0,3.9,3.9,3.8,3.8,...,66.766379,66.602606,66.510781,66.334637,66.323613,66.248731,66.202532,66.108962,65.934979,65.812084
2206,TRAIN_2206,17,228.0,389.0,398.0,393.5,5.3,5.2,5.2,5.1,...,72.885385,72.734930,72.629823,72.454654,72.389570,72.271680,72.208433,72.070977,71.872453,71.870512

In [4]:
y_var = ['착과량(int)']
id_var = list(train.columns[2 : 6])
season = list(train.columns[6 : 95])
yuprokso = list(train.columns[95 :])

In [5]:
train_melt = train.melt(id_vars = ['ID'] + y_var + id_var, value_vars = season + yuprokso)
test_melt = test.melt(id_vars = ['ID'] + id_var, value_vars = season + yuprokso)

train_melt['date'] = train_melt['variable'].apply(lambda x: x.split(' ')[0])
train_melt['type'] = train_melt['variable'].apply(lambda x: x.split(' ')[1])

test_melt['date'] = test_melt['variable'].apply(lambda x: x.split(' ')[0])
test_melt['type'] = test_melt['variable'].apply(lambda x: x.split(' ')[1])

In [6]:
train_melt

,ID,착과량(int),수고(m),수관폭1(min),수관폭2(max),수관폭평균,variable,value,date,type
0,TRAIN_0000,692,275.0,287.0,292.0,289.5,2022-09-01 새순,2.800000,2022-09-01,새순
1,TRAIN_0001,534,293.0,284.0,336.0,310.0,2022-09-01 새순,3.300000,2022-09-01,새순
2,TRAIN_0002,634,300.0,392.0,450.0,421.0,2022-09-01 새순,3.000000,2022-09-01,새순
3,TRAIN_0003,639,289.0,368.0,379.0,373.5,2022-09-01 새순,3.100000,2022-09-01,새순
4,TRAIN_0004,496,306.0,353.0,358.0,355.5,2022-09-01 새순,3.700000,2022-09-01,새순
...,...,...,...,...,...,...,...,...,...,...
392841,TRAIN_2202,119,230.0,353.0,367.0,360.0,2022-11-28 엽록소,65.560547,2022-11-28,엽록소
392842,TRAIN_2203,611,266.0,337.0,400.0,368.5,2022-11-28 엽록소,72.944396,2022-11-28,엽록소
392843,TRAIN_2204,650,237.0,353.0,362.0,357.5,2022-11-28 엽록소,66.479459,2022-11-28,엽록소
392844,TRAIN_2205,363,281.0,337.0,403.0,370.0,2022-11-28 엽록소,65.812084,2022-11-28,엽록소
392845,TRAIN_2206,17,228.0,389.0,398.0,393.5,2022-11-28 엽록소,71.870512,2022-11-28,엽록소

In [7]:
train_melt_preproc = train_melt[['ID'] + y_var + id_var + ['date']].drop_duplicates().reset_index(drop = True).merge(
    train_melt[train_melt['type'] == '새순'][['ID', 'date', 'value']].rename(columns = {'value' : '새순'}), how = 'left'
).merge(
    train_melt[(train_melt['type'] == '새순') & (train_melt['date'] == '2022-09-01')][['ID', 'value']].rename(columns = {'value' : '새순0'}), how = 'left'    
).merge(
    train_melt[(train_melt['type'] == '새순') & (train_melt['date'] == '2022-10-15')][['ID', 'value']].rename(columns = {'value' : '새순1'}), how = 'left'
).merge(
    train_melt[train_melt['type'] == '엽록소'][['ID', 'date', 'value']].rename(columns = {'value' : '엽록소'}), how = 'left'
)

train_melt_preproc['새순diff0'] = train_melt_preproc['새순'] - train_melt_preproc['새순0']
train_melt_preproc['새순diff1'] = train_melt_preproc['새순'] - train_melt_preproc['새순1']
train_melt_preproc['엽록소_새순'] = train_melt_preproc['엽록소'] / (train_melt_preproc['새순'] + 0.1) # 분모 0 방지

In [9]:
test_melt_preproc = test_melt[['ID'] + id_var + ['date']].drop_duplicates().reset_index(drop = True).merge(
    test_melt[test_melt['type'] == '새순'][['ID', 'date', 'value']].rename(columns = {'value' : '새순'}), how = 'left'
).merge(
    test_melt[(test_melt['type'] == '새순') & (test_melt['date'] == '2022-09-01')][['ID', 'value']].rename(columns = {'value' : '새순0'}), how = 'left'
).merge(
    test_melt[(test_melt['type'] == '새순') & (test_melt['date'] == '2022-10-15')][['ID', 'value']].rename(columns = {'value' : '새순1'}), how = 'left'
).merge(
    test_melt[test_melt['type'] == '엽록소'][['ID', 'date', 'value']].rename(columns = {'value' : '엽록소'}), how = 'left'
)

test_melt_preproc['새순diff0'] = test_melt_preproc['새순'] - test_melt_preproc['새순0']
test_melt_preproc['새순diff1'] = test_melt_preproc['새순'] - test_melt_preproc['새순1']
test_melt_preproc['엽록소_새순'] = test_melt_preproc['엽록소'] / (test_melt_preproc['새순'] + 0.1) # 분모 0 방지

In [10]:
display(train_melt_preproc)
display(test_melt_preproc)

,ID,착과량(int),수고(m),수관폭1(min),수관폭2(max),수관폭평균,date,새순,새순0,새순1,엽록소,새순diff0,새순diff1,엽록소_새순
0,TRAIN_0000,692,275.0,287.0,292.0,289.5,2022-09-01,2.8,2.8,1.7,78.336504,0.0,1.1,27.012587
1,TRAIN_0001,534,293.0,284.0,336.0,310.0,2022-09-01,3.3,3.3,1.9,80.116691,0.0,1.4,23.563733
2,TRAIN_0002,634,300.0,392.0,450.0,421.0,2022-09-01,3.0,3.0,1.8,79.118529,0.0,1.2,25.522106
3,TRAIN_0003,639,289.0,368.0,379.0,373.5,2022-09-01,3.1,3.1,1.9,77.936262,0.0,1.2,24.355082
4,TRAIN_0004,496,306.0,353.0,358.0,355.5,2022-09-01,3.7,3.7,2.1,76.233231,0.0,1.6,20.061377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196418,TRAIN_2202,119,230.0,353.0,367.0,360.0,2022-11-28,0.0,4.7,2.5,65.560547,-4.7,-2.5,655.605473
196419,TRAIN_2203,611,266.0,337.0,400.0,368.5,2022-11-28,0.6,3.1,1.9,72.944396,-2.5,-1.3,104.206281
196420,TRAIN_2204,650,237.0,353.0,362.0,357.5,2022-11-28,0.5,3.0,1.8,66.479459,-2.5,-1.3,110.799099
196421,TRAIN_2205,363,281.0,337.0,403.0,370.0,2022-11-28,0.0,3.9,2.2,65.812084,-3.9,-2.2,658.120840
196422,TRAIN_2206,17,228.0,389.0,398.0,393.5,2022-11-28,0.0,5.3,2.8,71.870512,-5.3,-2.8,718.705120

,ID,수고(m),수관폭1(min),수관폭2(max),수관폭평균,date,새순,새순0,새순1,엽록소,새순diff0,새순diff1,엽록소_새순
0,TEST_0000,231.0,219.0,302.0,260.5,2022-09-01,4.3,4.3,2.3,80.299924,0.0,2.0,18.249983
1,TEST_0001,206.0,324.0,346.0,335.0,2022-09-01,2.5,2.5,1.6,75.389791,0.0,0.9,28.996074
2,TEST_0002,282.0,373.0,404.0,388.5,2022-09-01,4.7,4.7,2.6,82.042248,0.0,2.1,17.092135
3,TEST_0003,234.0,337.0,357.0,347.0,2022-09-01,3.6,3.6,2.1,81.213424,0.0,1.5,21.949574
4,TEST_0004,222.0,329.0,347.0,338.0,2022-09-01,2.7,2.7,1.7,80.665529,0.0,1.0,28.809118
...,...,...,...,...,...,...,...,...,...,...,...,...,...
196507,TEST_2203,217.0,265.0,288.0,276.5,2022-11-28,0.6,2.5,1.5,69.601365,-1.9,-0.9,99.430521
196508,TEST_2204,182.0,191.0,262.0,226.5,2022-11-28,0.0,4.1,2.3,65.632342,-4.1,-2.3,656.323420
196509,TEST_2205,254.0,280.0,332.0,306.0,2022-11-28,0.6,3.8,2.2,62.307955,-3.2,-1.6,89.011365
196510,TEST_2206,257.0,285.0,297.0,291.0,2022-11-28,0.0,4.5,2.5,63.343589,-4.5,-2.5,633.435889
196511,TEST_2207,244.0,380.0,391.0,385.5,2022-11-28,0.0,4.9,2.7,64.025473,-4.9,-2.7,640.254730

In [11]:
train_df = train_melt_preproc.pivot(index = ['ID'] + y_var + id_var, columns = ['date'], values = ['새순diff0', '새순diff0', '새순', '엽록소_새순']).reset_index()
test_df = test_melt_preproc.pivot(index = ['ID'] + id_var, columns = ['date'], values = ['새순diff0', '새순diff0', '새순', '엽록소_새순']).reset_index()

In [12]:
display(train_df)
display(test_df)

              ID 착과량(int)  수고(m) 수관폭1(min) 수관폭2(max)  수관폭평균    새순diff0  \
date                                                        2022-09-01
0     TRAIN_0000      692  275.0     287.0     292.0  289.5        0.0
1     TRAIN_0001      534  293.0     284.0     336.0  310.0        0.0
2     TRAIN_0002      634  300.0     392.0     450.0  421.0        0.0
3     TRAIN_0003      639  289.0     368.0     379.0  373.5        0.0
4     TRAIN_0004      496  306.0     353.0     358.0  355.5        0.0
...          ...      ...    ...       ...       ...    ...        ...
2202  TRAIN_2202      119  230.0     353.0     367.0  360.0        0.0
2203  TRAIN_2203      611  266.0     337.0     400.0  368.5        0.0
2204  TRAIN_2204      650  237.0     353.0     362.0  357.5        0.0
2205  TRAIN_2205      363  281.0     337.0     403.0  370.0        0.0
2206  TRAIN_2206       17  228.0     389.0     398.0  393.5        0.0

                                       ...     엽록소_새순                         \
date 2022-09-02 2022-09-03 2022-09-04  ... 2022-11-19 2022-11-20  2022-11-21
0           0.0       -0.1       -0.1  ...  70.978249  78.751993   78.561392
1           0.0        0.0       -0.1  ...  89.419354  89.227879  101.790862
2          -0.1       -0.1       -0.1  ...  79.199782  79.110633   88.930026
3          -0.1       -0.1       -0.1  ...  69.934615  69.884124   69.845683
4          -0.1       -0.1       -0.1  ...  68.313016  68.285364   75.788734
...         ...        ...        ...  ...        ...        ...         ...
2202       -0.1       -0.2       -0.2  ...  73.719315  73.659565   73.547924
2203       -0.1       -0.1       -0.1  ...  73.438844  73.432194   81.505773
2204        0.0       -0.1       -0.1  ...  75.084518  74.893718   84.242512
2205        0.0       -0.1       -0.1  ...  74.184866  74.002895   73.900868
2206       -0.1       -0.1       -0.2  ...  72.885385  80.816588   80.699804

                                                                              \
date  2022-11-22  2022-11-23  2022-11-24  2022-11-25  2022-11-26  2022-11-27
0      78.399559   88.034195   87.925614   87.867287   87.828027   87.712301
1     101.560951  101.365154  117.994384  705.975500  705.650877  705.605022
2      88.783425   88.650048   88.595904  101.014470  100.851388  100.597433
3      77.549647   77.533125   77.349604   77.172671   86.601987   86.548361
4      75.788286   75.600092   84.824954   84.719445   84.626821   96.434635
...          ...         ...         ...         ...         ...         ...
2202   82.720738   82.637306   94.298249   94.128107  109.556776  655.866556
2203   81.477213   81.412624   91.360938   91.339631   91.336295   91.190699
2204   84.059285   83.896281   83.667214   95.335168   95.102994   95.008580
2205   82.918297   82.904517   82.810913   94.575046   94.441374  109.891631
2206   90.568318   90.486962  103.245257  103.154904  120.118295  718.724532


date  2022-11-28
0     100.061788
1     704.276003
2     117.332631
3      86.417462
4      96.300133
...          ...
2202  655.605473
2203  104.206281
2204  110.799099
2205  658.120840
2206  718.705120

[2207 rows x 362 columns]

             ID  수고(m) 수관폭1(min) 수관폭2(max)  수관폭평균    새순diff0             \
date                                              2022-09-01 2022-09-02
0     TEST_0000  231.0     219.0     302.0  260.5        0.0       -0.1
1     TEST_0001  206.0     324.0     346.0  335.0        0.0        0.0
2     TEST_0002  282.0     373.0     404.0  388.5        0.0        0.0
3     TEST_0003  234.0     337.0     357.0  347.0        0.0        0.0
4     TEST_0004  222.0     329.0     347.0  338.0        0.0        0.0
...         ...    ...       ...       ...    ...        ...        ...
2203  TEST_2203  217.0     265.0     288.0  276.5        0.0        0.0
2204  TEST_2204  182.0     191.0     262.0  226.5        0.0        0.0
2205  TEST_2205  254.0     280.0     332.0  306.0        0.0        0.0
2206  TEST_2206  257.0     285.0     297.0  291.0        0.0       -0.1
2207  TEST_2207  244.0     380.0     391.0  385.5        0.0       -0.1

                                       ...     엽록소_새순                        \
date 2022-09-03 2022-09-04 2022-09-05  ... 2022-11-19 2022-11-20 2022-11-21
0          -0.1       -0.2       -0.2  ...  80.101663  79.895751  89.858498
1           0.0        0.0        0.0  ...  76.026418  75.948000  75.940863
2          -0.1       -0.1       -0.2  ...  74.435783  82.497186  82.380738
3           0.0        0.0       -0.1  ...  81.745262  81.578048  91.641922
4           0.0        0.0       -0.1  ...  72.216758  80.181281  80.058836
...         ...        ...        ...  ...        ...        ...        ...
2203       -0.1       -0.1       -0.1  ...  78.408851  78.365291  78.148783
2204        0.0       -0.1       -0.1  ...  73.939931  73.872953  83.010468
2205        0.0       -0.1       -0.1  ...  63.254101  63.134023  70.039310
2206       -0.1       -0.2       -0.2  ...  64.331650  71.264298  71.161281
2207       -0.1       -0.2       -0.2  ...  72.482251  72.266993  81.230092

                                                                             \
date 2022-11-22  2022-11-23  2022-11-24  2022-11-25  2022-11-26  2022-11-27
0     89.823399  102.465058  102.188025  102.109907  118.868729  711.842952
1     75.764621   84.994041   84.849947   84.681025   84.591902   96.485675
2     92.588001   92.365510  105.423062  105.165482  122.400227  733.870508
3     91.436622   91.386998  104.177872  104.067730  104.054662  121.120260
4     79.895535   79.740157   89.683516   89.586059   89.376304   89.274643
...         ...         ...         ...         ...         ...         ...
2203  87.806407   87.733332   87.512774   87.395934   99.673889   99.625354
2204  82.818921   94.580929   94.399417   94.215728  109.808313  657.197872
2205  69.864439   69.645946   78.124669   78.027377   78.021494   89.034233
2206  79.930387   79.895729   79.747262   91.089600  106.136221  635.121136
2207  81.030417   92.459212   92.289771  107.569702  643.673567  641.979751


date  2022-11-28
0     710.002231
1      96.354070
2     732.283192
3     725.381714
4      89.160280
...          ...
2203   99.430521
2204  656.323420
2205   89.011365
2206  633.435889
2207  640.254730

[2208 rows x 361 columns]

In [13]:
vars = []
for x in train_df.columns:
    if x[1] == '':
        vars.append(x[0])
    else:
        vars.append(x[0] + '' + x[1])

train_df.columns = vars
test_df.columns = ['ID'] + vars[2:]

In [14]:
train_x, valid_x, train_y, valid_y = train_test_split(train_df.iloc[:, 2:], train_df[y_var], test_size = 0.4, random_state = 1740)

In [15]:
rf = RandomForestRegressor(max_depth = 5, random_state = 1740, n_estimators = 200)
rf.fit(pd.concat([train_x, valid_x], axis = 0).iloc[:, 4:], pd.concat([train_y, valid_y], axis = 0).to_numpy().reshape(-1))

RandomForestRegressor(max_depth=5, n_estimators=200, random_state=1740)

In [ ]:
pd.DataFrame({
    'ID' : test_df['ID'],
    '착과량(int)' : np.array(np.round(rf.predict(test_df.iloc[:, 5:]), 0), dtype = 'int')
}).to_csv('submit.csv', index = False)